---
###
### GVM-CLI Wrapper
###

- name: "GVM-CLI Wrapper"
  hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: "gvm admin pass"
      set_fact:
        gvm_admin_pass: "{{ lookup('password', '/etc/ansible/saved_passwd/local_gvm_admin_password' ) }}"

    - name: "Set permissions"
      file:
        mode: "0777"
        path: "/tmp/ansible"
        state: "directory"

    - name: Populate the input XML file from a template
      template:
        src: "../templates/gvm_xml_inputs/{{ scan_command }}.xml.j2"
        dest: "/tmp/ansible/{{ sqs_message_id | default('gvm-cli') }}-{{ scan_command }}.xml"

    - name: "Run gvm-cli"
      become: yes
      become_user: "gvm"
      register: scan_output
      no_log: true
      ignore_errors: yes
      args:
        executable: "/bin/bash"
      shell: |
              /usr/local/bin/gvm-cli --timeout 300 --gmp-username=admin --gmp-password='{{ gvm_admin_pass }}' socket --socketpath /var/run/gvm/gvmd.sock /tmp/ansible/{{ sqs_message_id | default('gvm-cli') }}.xml

    - name: "Record the stdout to a file"
      copy:
        dest: "/tmp/ansible/{{ sqs_message_id | default('scan_output') }}-output.xml"
        content: "{{ scan_output.stdout }}"

    - name: "Record the stderr to a file"
      copy:
        dest: "/tmp/ansible/{{ sqs_message_id | default('scan_output') }}-error.txt"
        content: "{{ scan_output.stderr }}"

    - name: "Upload to S3 bucket"
      aws_s3:
        bucket: "{{ scan_result_bucket }}"
        aws_access_key: "{{ ansible_local.secureops.customer_info.aws_key_id }}"
        aws_secret_key: "{{ ansible_local.secureops.customer_info.aws_sec_key }}"
        region: "{{ ansible_local.secureops.customer_info.aws_region }}"
        object: "scan_results/{{ ansible_local.secureops.customer_info.name }}/{{ ansible_local.secureops.customer_info.node }}/{{ item }}"
        mode: put
        src: "/tmp/ansible/{{ item }}"
      when: scan_result_bucket is defined
      loop:
        - "{{ sqs_message_id | default('scan_output') }}-output.xml"
        - "{{ sqs_message_id | default('scan_output') }}-error.txt"


    #- name: "Remove scan temp files"
    #  file:
    #    path: "/tmp/ansible/{{ sqs_message_id | default('scan_output') }}-*"
    #    state: "absent"
