---
###
### GVM-CLI Wrapper
###

- name: "GVM-CLI Wrapper"
  hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: "gvm admin pass"
      set_fact:
        gvm_admin_pass: "{{ lookup('password', '/etc/ansible/saved_passwd/local_gvm_admin_password' ) }}"

    - name: "Set permissions"
      file:        
        mode: "0777"
        path: "/tmp/ansible"
        state: "directory"

    - name: "Run gvm-cli"
      become: yes
      become_user: "gvm"
      args:
        executable: "/bin/bash"
      shell: |
              /usr/local/bin/gvm-cli --gmp-username=admin --gmp-password='{{ gvm_admin_pass }}' socket --socketpath /var/run/gvm/gvmd.sock --xml "<get_version/>"



 



