---
###
### GVM-CLI Wrapper
###

- name: "GVM-CLI Wrapper"
  hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: "gvm admin pass"
      set_fact:
        gvm_admin_pass: "{{ lookup('password', '/etc/ansible/saved_passwd/local_gvm_admin_password' ) }}"

    - name: "Set permissions"
      file:
        mode: "0777"
        path: "/tmp/ansible"
        state: "directory"
    - name: Populate the input XML file from a template
      template:
        src: "../templates/gvm_xml_inputs/{{ scan_command }}.xml.j2"
        dest: "/tmp/ansible/{{ scan_command }}.xml"
    - name: "Run gvm-cli"
      become: yes
      become_user: "gvm"
      args:
        executable: "/bin/bash"
      shell: |
              /usr/local/bin/gvm-cli --gmp-username=admin --gmp-password='{{ gvm_admin_pass }}' socket --socketpath /var/run/gvm/gvmd.sock /tmp/ansible/{{ scan_command }}.xml
      register: scan_output
    - name: "Remove scan command XML"
      file:
        path: "/tmp/ansible/{{ scan_command }}.xml"
        state: "absent"
    - name: Record the output to a file
      copy:
        dest: "/tmp/ansible/{{ sqs_message_id | default('scan_output') }}.xml"
        content: "{{ scan_output.stdout }}"
    - name: Upload to S3 bucket
      aws_s3:
        bucket: "{{ scan_result_bucket }}"
        region: "{{ ansible_local.secureops.customer_info.aws_region }}"
        object: "scan_results/{{ ansible_local.secureops.customer_info.name }}/{{ ansible_local.secureops.customer_info.node_name }}/{{ sqs_message_id }}.xml"
        mode: put
        src: "/tmp/ansible/{{ sqs_message_id | default('scan_output') }}.xml"
      when: scan_result_bucket is defined
    - name: "Remove scan result when an S3 bucket is defined"
      file:
        path: "/tmp/ansible/{{ sqs_message_id | default('scan_output') }}.xml"
        state: "absent"
