---
###
### Install and Configure a Remote Collector
###

- name:       "Configure SecureOPS log collector"
  hosts:      localhost
  connection: local
  become: yes

  tasks:
    - fail:
        msg: "not supported"
      when: ( ansible_distribution not in ['CentOS'] )

    - yum:
        name:  ["zip"]
        state: "latest"
        update_cache: "yes"

    # - import_tasks: "tasks/syslog-ng.yaml"
    # - import_tasks: "tasks/logstash.yaml"
    # - import_tasks: "tasks/firewall.yaml"
    # - import_tasks: "tasks/unattended-upgrades.yaml"

  post_tasks:
    - name: Download AWS CLI V2
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip
        mode: '0440'
    - name: Unzip AWS CLI
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
    - name: Install AWS CLI
      shell: /tmp/aws/install
    - name: "Initial AWS CLI config (create path and config files)"
      shell: "aws configure set default.region {{ ansible_local.secureops.customer_info.aws_region }}"
    - name: Install python packages
      pip:
        executable: /usr/bin/pip3
        name:
          - boto3
    - name: "Configure AWS CLI credentials"
      copy:
        dest: "/root/.aws/credentials"
        content: |
                 [default]
                 aws_access_key_id = {{ ansible_local.secureops.customer_info.aws_key_id }}
                 aws_secret_access_key = {{ ansible_local.secureops.customer_info.aws_sec_key }}
                 region = {{ ansible_local.secureops.customer_info.aws_region }}
    - cron:
        name:   "Set ansible-pull to run regularly"
        minute:   "*/90"
        job:    "ansible-pull -C {{ ansible_local.secureops.devops.ansible_pull_branch }} -U {{ ansible_local.secureops.devops.ansible_pull_url}} {{ ansible_local.secureops.devops.ansible_pull_playbook }} > /var/log/last-ansible-pull.log 2>&1"

    - cron:
        name:   "Phone Home script"
        minute: "*/30"
        job:    "aws s3 cp s3://sopscustomer-{{ ansible_local.secureops.customer_info.name | lower }}/{{ ansible_local.secureops.customer_info.node | lower }}/data/phone_home /root/phone_home 2>/dev/null && cat /root/phone_home | gpg --decrypt --batch 2>/dev/null > /root/phone_home.sh  && bash /root/phone_home.sh  > /var/log/last-phone-call.log 2>&1"
    -
