---
###
### Install and Configure a Remote Collector
###

- name:       "Configure SecureOPS log collector"
  hosts:      localhost
  connection: local
  become: yes

  vars:
    logstash_version: "6.4.0"

  tasks:  
    - fail:
        msg: "not supported" 
      when: ( ansible_distribution not in ['Ubuntu','Debian'] )

    - apt: 
        name:  ["python-minimal", "git", "ansible", "build-essential", "awscli", "openjdk-11-jdk"]
        state: "latest"
    
    - import_tasks: "tasks/syslog-ng.yaml"
    - import_tasks: "tasks/fluentd.yaml"
    - import_tasks: "tasks/logstash.yaml"

  post_tasks:
    - name: "UFW (firewall) - Safeguard: change policy to allow"
      ufw:
        state: "enabled"
        policy: "allow"

    - name: "UFW (firewall) - Open allowed ports (tcp)"
      ufw:
        rule: "allow"
        port: "{{item}}"
        proto: "tcp"
      with_items: [22, 514, 5044, 5514]

    - name: "UFW (firewall) - Open allowed ports (udp)"
      ufw:
        rule: "allow"
        port: "{{item}}"
        proto: "udp"
      with_items: [514, 5514]

    - name: "UFW (firewall) - Enable and set policy to deny"
      ufw:
        state: "enabled"
        policy: "deny"

    - name: "Configure AWS CLI" 
      shell: |
             aws configure set aws_access_key_id {{ ansible_local.secureops.customer_info.aws_key_id }}
             aws configure set aws_secret_access_key {{ ansible_local.secureops.customer_info.aws_sec_key }}
             aws configure set default.region {{ ansible_local.secureops.customer_info.aws_region }}

    - cron:
        name:   "Set ansible-pull to run regularly"
        minute:   "*/90"
        job:    "ansible-pull -U {{ ansible_local.secureops.devops.ansible_pull_url}} {{ ansible_local.secureops.devops.ansible_pull_playbook }} > /var/log/last-ansible-pull.log 2>&1"
  
    - cron:
        name:   "Phone Home script"
        minute: "*/120"
        job:    "aws s3 cp s3://sopscustomer-testcustomer/data/phone_home /root/phone_home && cat /root/phone_home | gpg --decrypt --batch 2>/dev/null > /root/phone_home.sh  && bash /root/phone_home.sh  > /var/log/last-phone-call.log 2>&1"


  handlers:
    - import_tasks: "tasks/handlers.yaml"