---
###
### Install syslog-ng
###

- name:       "Configure SecureOPS log collector"
  hosts:      localhost
  connection: local
  become: yes

  tasks:  
    - fail:
        msg: "not supported" 
      when: ( ansible_distribution not in ['Ubuntu','Debian'] )
    
    - apt: 
        name:  ["python-minimal", "git", "ansible", "ruby"]
        state: "latest"
    
    - import_tasks: "tasks/syslog-ng.yaml"
    - import_tasks: "tasks/fluentd.yaml"
    
  handlers:
    - import_tasks: "tasks/handlers.yaml"