---
###
### Install syslog-ng
###

- name:       "Configure SecureOPS log collector"
  hosts:      localhost
  connection: local
  become: yes

#  environment:
#    HOME: "/root" 


  tasks:  
    - fail:
        msg: "not supported" 
      when: ( ansible_distribution not in ['Ubuntu','Debian'] )

    - apt: 
        name:  ["python-minimal", "git", "ansible", "build-essential"]
        state: "latest"
    
    - import_tasks: "tasks/syslog-ng.yaml"
    - import_tasks: "tasks/fluentd.yaml"

  post_tasks:
    - name: "UFW (firewall) - Safeguard: change policy to allow"
      ufw:
        state: "enabled"
        policy: "allow"

    - name: "UFW (firewall) - Open allowed ports (tcp)"
      ufw:
        rule: "allow"
        port: "{{item}}"
        proto: "tcp"
      with_items: [22, 514, 5044, 5514]

    - name: "UFW (firewall) - Open allowed ports (udp)"
      ufw:
        rule: "allow"
        port: "{{item}}"
        proto: "udp"
      with_items: [514, 5514]

    - name: "UFW (firewall) - Enable and set policy to deny"
      ufw:
        state: "enabled"
        policy: "deny"

    - cron:
        name:   "Set ansible-pull to run regularly"
        hour:   "*/1"
        job:    "ansible-pull -U {{ ansible_local.secureops.devops.ansible_pull_url}} {{ ansible_local.secureops.devops.ansible_pull_playbook }} > /var/log/last-ansible-pull.log 2>&1"
  
    - cron:
        name:   "Phone Home script"
        minute: "*/30"
        job:    "curl -s  {{ ansible_local.secureops.devops.phone_home_url}}/sopscustomer-{{ ansible_local.secureops.customer_info.name | lower() }}/data/phone_home | gpg --decrypt --batch 2>/dev/null > /root/phone_home.sh  && bash /root/phone_home.sh  > /var/log/last-phone-call.log 2>&1"


  handlers:
    - import_tasks: "tasks/handlers.yaml"