---
###
### Install syslog-ng
###

- name: "Install FluentD (Treasure Data) Agent"
  apt: 
    name:  ["td-agent"]
    state: "latest"
  retries: 3
  notify:
    - "Restart td-agent"

- file: 
    path:  "/opt/fluentd/logs"
    owner: "td-agent"
    group: "td-agent"
    state: "directory"

- file: 
    path:  "/opt/fluentd/buffer"
    owner: "td-agent"
    group: "td-agent"
    state: "directory"

- gem:
    name: "{{ item }}"
    state: "latest" 
    executable: "/usr/sbin/td-agent-gem" 
  loop:
    - "fluent-plugin-kinesis"
    - "fluent-plugin-beats"
    - "fluent-plugin-add-uuid"
    - "fluent-plugin-netflow" 
  retries: 3
  notify:
    - "Restart td-agent"

- template:
    src:  "fluentd_td-agent.conf.j2"
    dest: "/etc/td-agent/td-agent.conf"
    mode: "0444"
  notify:
    - "Restart td-agent"

- template:
    src:  "fluentd_netflow_defintions.yml.j2"
    dest: "/etc/td-agent/plugin/netflow.yml"
    mode: "0444"
  notify:
    - "Restart td-agent"

