---
###
### Install GVM (OpenVAS)
###

- name: "Install Atomic Repositories"
  ignore_errors: true
  shell: | 
         export NON_INT=1
         wget -q -O - https://updates.atomicorp.com/installers/atomic | sh

- name: "Enable Required Repositories"
  yum_repository:
    name: "PowerTools"
    enabled: true

- name: "Install Pre-req packages"
  yum:
    name: "epel-release"
    state: "latest"
    update_cache: "yes"

- name: "Install packages"
  yum:
    name: "gvm"
    state: "latest"
    update_cache: "yes"
