---
###
### Install Logstash
###

- name: "Pinning Elasticsearch version (DEB)"
  tags: ["pinning"]
  copy:
    dest: "/etc/apt/preferences.d/logstash"
    content: |
      Package: logstash
      Pin: version 1:{{ logstash_version }}*
      Pin-Priority: 900

- name: "Install Logstash"
  apt: 
    name:  ["logstash=1:{{logstash_version}}*"]
    state: "present"
  retries: 3
  notify:
    - "Restart logstash"

- name: "Configure AWS CLI" 
  shell: |
         aws configure set aws_access_key_id {{ ansible_local.secureops.customer_info.aws_key_id }}
         aws configure set aws_secret_access_key {{ ansible_local.secureops.customer_info.aws_sec_key }}
         aws configure set default.region {{ ansible_local.secureops.customer_info.aws_region }}

- file: 
    path:  "/opt/logstash/logs"
    owner: "logstash"
    group: "logstash"
    state: "directory"

- file: 
    path:  "/opt/logstash/data"
    owner: "logstash"
    group: "logstash"
    state: "directory"

#######
#######
## Install logstash plugins
##
- shell: "/usr/share/logstash/bin/logstash-plugin  list | grep -i logstash-filter-uuid"
  ignore_errors: "yes"
  register: shell_result
- name: "Install logstash-filter-uuid plugins... " 
  shell: "/usr/share/logstash/bin/logstash-plugin install logstash-filter-uuid"
  when:  ( shell_result.rc != 0 )
  retries: 3
  
- shell: "/usr/share/logstash/bin/logstash-plugin  list | grep -i logstash-output-kinesis"
  ignore_errors: "yes"
  register: shell_result
- name: "Install logstash-output-kinesis plugins... " 
  shell: "/usr/share/logstash/bin/logstash-plugin install logstash-output-kinesis"
  when:  ( shell_result.rc != 0 )
  retries: 3
##
##
##
######
######

- template:
    src:  "logstash_sops-remoteCollector.conf.j2"
    dest: "/etc/logstash/conf.d/sops-remoteCollector.conf"
    mode: "0444"
  notify:
    - "Restart logstash"

- template:
    src:  "logstash_logstash.yml.j2"
    dest: "/etc/logstash/logstash.yml"
    mode: "0444"
  notify:
    - "Restart logstash"
    
- name: "Enable Logstash Service"
  service: 
   name:  "logstash"
   enabled: "yes"
