---
###
### Install syslog-ng
###

- name: "Install Syslog-NG"
  apt: 
    name:  ["syslog-ng"]
    state: "latest"
  #notify:
  #  - "Restart logstash"

##    - file: 
##        path:  "/data/logstash"
##        owner: "logstash"
##        group: "logstash"
##        state: "directory"
##
##    - template:
##        src:  "templates/logstash.yml.j2"
##        dest: "/etc/logstash/logstash.yml"
##        mode: "0444"
##      notify: ["Restart logstash"]
##      
##    - template:
##        src:  "templates/logstash_pipeline.conf.j2"
##        dest: "/etc/logstash/conf.d/pipeline.conf"
##        mode: "0444"
##      notify: ["Restart logstash"]
##
##    - service: 
##        name:    "logstash"
##        state:   "started"
##        enabled: "yes"
##
##  handlers:
##    - name: "Restart logstash"
##      service: 
##        name:  "logstash"
##        state: "restarted"
